### ISSUE TITLE
GraphQL 

### ISSUE THREAD

**Issue by devalexandre** [elemencast/elemencast.github.io#2]
seria interesante mais conteudo sobre a nova tendencia em API , GraphQL é algo muito poderoso e que facilita muito o desenvolvimento

**Comment by kevinbreaker** [comment]
Verdade, abordar o GraphQL seria uma boa.

**Comment by luiguild** [comment]
Valeu pela participação de vocês @devalexandre e @kevinbreaker! Eu amo Graphql e pretendo sim fazer um episódio só sobre ele, gostariam de sugerir algo pra que eu adicione no conteúdo? :D
