### ISSUE TITLE
Flutter - Dart

### ISSUE THREAD

**Issue by kevinbreaker** [elemencast/elemencast.github.io#3]
Falar sobre o Flutter e um pouco da linguagem Dart será interessante. Até pelo fato do Flutter ser algo novo e mal ter conteúdo em Português.

**Comment by devalexandre** [comment]
realmente seria bacana estou fazendo uns testes com ele e me parece bem viável , uma alternativa ao react-native.

**Comment by luiguild** [comment]
Fala @kevinbreaker e @devalexandre! Valeu por comentarem aqui! <3 Honestamente não gosto de dart e não pretendo falar sobre isso no elemencast :( sem contar que acho Flutter pequeno e cru demais ainda... Se for pra abordar esse tema, ainda prefiro React Native e Vue NativeScript. Porém, como sempre costumo dizer, estou aberto a aprender sobre se por acaso vocês tiveram algo completamente novo e relevante pra mostrar sobre o assunto <3
