### ISSUE TITLE
PreactJS

### ISSUE THREAD

**Issue by devalexandre** [elemencast/elemencast.github.io#4]
andei vendo o practJS e ate mesmo irei usar ele no meu curso de adianti framework , achei bem interessante, e ja para poupar o issue  caso for ter esse de tema, seria interessante algo sobre o fim do redux e o que sera usado no lugar dele ou as alternativas 👍

**Comment by luiguild** [comment]
Fala @devalexandre valeu por ter aberto a issue! Honestamente não conheço nada de Preact e acho que nessa 'linha'/'família' de tipos de frameworks js, acredito que seja melhor concentrar tudo em React mesmo. Sobre o fim do Redux, até hoje não vi nada concreto sobre, apenas os pensamentos da nova forma que pretende ser... Tem alguma informação válida? Abraço!
