### ISSUE TITLE
Microfrontend

### ISSUE THREAD

**Issue by alexsandro-xpt** [elemencast/elemencast.github.io#6]
Que tal fazer um podcast sobre o assunto de Microfrontend?

**Comment by luiguild** [comment]
Fala @alexsandro-xpt! Valeu pela sugestão, mas assim cara... esse assunto além de ser completamente cru, nunca vi nada consistente sobre ele... Tem algum material pra indicar? Abraço!

**Comment by alexsandro-xpt** [comment]
@luiguild existe algumas coisas sobre este assunto sim veja isto aqui: https://github.com/frontendbr/forum/issues/661

Tem muita coisa interessante ai como este projeto https://github.com/shershen08/tailor-vue-demo que usa uma Lib chamada Tailor.

O que você acha? Vale ou não vale uma atenção maior?

**Comment by luiguild** [comment]
Fala cara! Então, li a thread e vi o projeto. É legal? Pode ser. Tem futuro? Acho que não. Acho válido ter um episódio só sobre isso? Não.

Minhas considerações: ainda é cru demais o conceito no geral por si só e sem contar que com Atomic Design eu já tenho tudo isso aí que foi citado na thread... Hoje eu trabalho com um ambiente completamente independente em repositórios, inclusive, onde a aplicação importa diversos componentes independentes pra fazer o produto, por si só, acho overhead a forma com que tá sendo feito o Tailor-Vue, por mais que funcione e eu aprecio o empenho do pessoal em fazer funcionar, mas eu ainda acho que isso é over-engineering pra caralho... 

Por fim, não estou fechado a essa e outras inovações, eu amo inovações, só acho que essa ainda tem pouca coisa DEMAIS pra se dar essa atenção toda, dada a demanda pequena desse tipo de solução e também a curva necessária de implantação da parada... Se por a caso esse assunto evoluir ainda mais, pode ter certeza absoluta que ele terá espaço no elemencast ❤️ 

Obrigado pelas considerações!
